BSD2_24/Models/ErrorViewModel.cs
namespace BSD2_24.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BSD2_24/Models/Produit.cs
using System.ComponentModel.DataAnnotations;

namespace BSD2_24.Models
{
    public class Produit
    {
        public int Id { get; set; }
        public string? Nom { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateDeSortie { get; set; }

        public decimal Prix { get; set; }
    }
}

BSD2_24/Models/SeedData.cs
using BSD2_24.Data;
using Humanizer;
using Microsoft.EntityFrameworkCore;

namespace BSD2_24.Models
{
    public static class SeedData
    {
        public static void Initalize(IServiceProvider serviceProvider)
        {

            using (var context = new BSD2_24Context(
                serviceProvider.GetRequiredService<
                    DbContextOptions<BSD2_24Context>>()))
            {
                if (context.Produit.Any())
                {
                    return;
                }

                context.Produit.AddRange(

                    new Produit { 
                        Nom = "LaPizzaDeKoko",
                        DateDeSortie= DateTime.Parse("2015-02-08"),
                        Prix = 7.99M
                    },
                    new Produit { 
                        Nom = "LaDaronneDeKoko",
                        DateDeSortie = DateTime.Parse("1970-05-10"),
                        Prix = 119.99M
                    },
                    new Produit { 
                        Nom = "Koko",
                        DateDeSortie = DateTime.Parse("2005-12-04"),
                        Prix = 999.99M
                    },
                    new Produit { 
                        Nom = "LeDaronDeKoko",
                        DateDeSortie = DateTime.Parse("1969-06-06"),
                        Prix = 449.99M
                    },
                    new Produit { 
                        Nom = "LaSoeurDeKoko",
                        DateDeSortie = DateTime.Parse("2000-09-03"),
                        Prix = 249.99M
                    },
                    new Produit { 
                        Nom = "ChatDeKoko",
                        DateDeSortie = DateTime.Parse("2017-01-11"),
                        Prix = 20M
                    }

                    );

                context.SaveChanges();
            }
        }
    }
}

BSD2_24/Controllers/HomeController.cs
using System.Diagnostics;
using BSD2_24.Models;
using Microsoft.AspNetCore.Mvc;

namespace BSD2_24.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BSD2_24/Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BSD2_24.Data;
using BSD2_24.Models;

namespace BSD2_24.Controllers
{
    public class ProduitsController : Controller
    {
        private readonly BSD2_24Context _context;

        public ProduitsController(BSD2_24Context context)
        {
            _context = context;
        }

        // GET: Produits
        public async Task<IActionResult> Index(string recherche)
        {

            var produits = from p in _context.Produit
                           select p;

            if (!String.IsNullOrEmpty(recherche))
            {
                produits = produits.Where(p => p.Nom!.ToUpper().Contains(recherche.ToUpper()));
            }

            ViewData["recherche"] = recherche;


            return View(await produits.ToListAsync());
        }

        // GET: Produits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produit
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        // GET: Produits/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom,DateDeSortie,Prix")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produit);
        }

        // GET: Produits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produit.FindAsync(id);
            if (produit == null)
            {
                return NotFound();
            }
            return View(produit);
        }

        // POST: Produits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,DateDeSortie,Prix")] Produit produit)
        {
            if (id != produit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProduitExists(produit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produit);
        }

        // GET: Produits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produit
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        // POST: Produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produit = await _context.Produit.FindAsync(id);
            if (produit != null)
            {
                _context.Produit.Remove(produit);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProduitExists(int id)
        {
            return _context.Produit.Any(e => e.Id == id);
        }
    }
}

BSD2_24/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BSD2_24/Views/Produits/Create.cshtml
@model BSD2_24.Models.Produit

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Produit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateDeSortie" class="control-label"></label>
                <input asp-for="DateDeSortie" class="form-control" />
                <span asp-validation-for="DateDeSortie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prix" class="control-label"></label>
                <input asp-for="Prix" class="form-control" />
                <span asp-validation-for="Prix" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BSD2_24/Views/Produits/Delete.cshtml
@model BSD2_24.Models.Produit

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produit</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDeSortie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDeSortie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prix)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prix)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BSD2_24/Views/Produits/Details.cshtml
@model BSD2_24.Models.Produit

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Produit</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDeSortie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDeSortie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prix)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prix)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BSD2_24/Views/Produits/Edit.cshtml
@model BSD2_24.Models.Produit

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Produit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateDeSortie" class="control-label"></label>
                <input asp-for="DateDeSortie" class="form-control" />
                <span asp-validation-for="DateDeSortie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prix" class="control-label"></label>
                <input asp-for="Prix" class="form-control" />
                <span asp-validation-for="Prix" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BSD2_24/Views/Produits/Index.cshtml
@model IEnumerable<BSD2_24.Models.Produit>

@{
    ViewData["Title"] = "Index";
    var recherche = ViewData["recherche"] as string;
}

<h1>Index</h1>


<form asp-controller="Produits" asp-action="Index" method="get">
    <p>
        <input type="text" name="recherche" placeholder="Ex : Nom du produit" value="@recherche" />
        <input class="btn btn-primary" type="submit" value="Rechercher" />
    </p>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateDeSortie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prix)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateDeSortie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prix)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

BSD2_24/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BSD2_24</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BSD2_24.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BSD2_24</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produits" asp-action="Index">Produit</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - BSD2_24 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>